Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\asus\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dataPTA = pd.read_excel('PTAscrawl.xlsx')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m dataPTA [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_excel[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mPTAscrawl.xlsx[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [1;32mc:\users\asus\appdata\local\programs\python\python39\lib\site-packages\pandas\util\_decorators.py:311[0m, in [0;36mdeprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper[1;34m(*args, **kwargs)[0m
[0;32m    305[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(args) [38;5;241m>[39m num_allow_args:
[0;32m    306[0m     warnings[38;5;241m.[39mwarn(
[0;32m    307[0m         msg[38;5;241m.[39mformat(arguments[38;5;241m=[39marguments),
[0;32m    308[0m         [38;5;167;01mFutureWarning[39;00m,
[0;32m    309[0m         stacklevel[38;5;241m=[39mstacklevel,
[0;32m    310[0m     )
[1;32m--> 311[0m [38;5;28;01mreturn[39;00m func([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32mc:\users\asus\appdata\local\programs\python\python39\lib\site-packages\pandas\io\excel\_base.py:457[0m, in [0;36mread_excel[1;34m(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, thousands, decimal, comment, skipfooter, convert_float, mangle_dupe_cols, storage_options)[0m
[0;32m    455[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[0;32m    456[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m--> 457[0m     io [38;5;241m=[39m [43mExcelFile[49m[43m([49m[43mio[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m[43m [49m[43mengine[49m[38;5;241;43m=[39;49m[43mengine[49m[43m)[49m
[0;32m    458[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[0;32m    459[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    460[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[0;32m    461[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[0;32m    462[0m     )

File [1;32mc:\users\asus\appdata\local\programs\python\python39\lib\site-packages\pandas\io\excel\_base.py:1376[0m, in [0;36mExcelFile.__init__[1;34m(self, path_or_buffer, engine, storage_options)[0m
[0;32m   1374[0m     ext [38;5;241m=[39m [38;5;124m"[39m[38;5;124mxls[39m[38;5;124m"[39m
[0;32m   1375[0m [38;5;28;01melse[39;00m:
[1;32m-> 1376[0m     ext [38;5;241m=[39m [43minspect_excel_format[49m[43m([49m
[0;32m   1377[0m [43m        [49m[43mcontent_or_path[49m[38;5;241;43m=[39;49m[43mpath_or_buffer[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m
[0;32m   1378[0m [43m    [49m[43m)[49m
[0;32m   1379[0m     [38;5;28;01mif[39;00m ext [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m   1380[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m   1381[0m             [38;5;124m"[39m[38;5;124mExcel file format cannot be determined, you must specify [39m[38;5;124m"[39m
[0;32m   1382[0m             [38;5;124m"[39m[38;5;124man engine manually.[39m[38;5;124m"[39m
[0;32m   1383[0m         )

File [1;32mc:\users\asus\appdata\local\programs\python\python39\lib\site-packages\pandas\io\excel\_base.py:1250[0m, in [0;36minspect_excel_format[1;34m(content_or_path, storage_options)[0m
[0;32m   1247[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(content_or_path, [38;5;28mbytes[39m):
[0;32m   1248[0m     content_or_path [38;5;241m=[39m BytesIO(content_or_path)
[1;32m-> 1250[0m [38;5;28;01mwith[39;00m [43mget_handle[49m[43m([49m
[0;32m   1251[0m [43m    [49m[43mcontent_or_path[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m[43m [49m[43mis_text[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m
[0;32m   1252[0m [43m[49m[43m)[49m [38;5;28;01mas[39;00m handle:
[0;32m   1253[0m     stream [38;5;241m=[39m handle[38;5;241m.[39mhandle
[0;32m   1254[0m     stream[38;5;241m.[39mseek([38;5;241m0[39m)

File [1;32mc:\users\asus\appdata\local\programs\python\python39\lib\site-packages\pandas\io\common.py:798[0m, in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    789[0m         handle [38;5;241m=[39m [38;5;28mopen[39m(
[0;32m    790[0m             handle,
[0;32m    791[0m             ioargs[38;5;241m.[39mmode,
[1;32m   (...)[0m
[0;32m    794[0m             newline[38;5;241m=[39m[38;5;124m"[39m[38;5;124m"[39m,
[0;32m    795[0m         )
[0;32m    796[0m     [38;5;28;01melse[39;00m:
[0;32m    797[0m         [38;5;66;03m# Binary mode[39;00m
[1;32m--> 798[0m         handle [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mhandle[49m[43m,[49m[43m [49m[43mioargs[49m[38;5;241;43m.[39;49m[43mmode[49m[43m)[49m
[0;32m    799[0m     handles[38;5;241m.[39mappend(handle)
[0;32m    801[0m [38;5;66;03m# Convert BytesIO or file objects passed with an encoding[39;00m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'PTAscrawl.xlsx'
FileNotFoundError: [Errno 2] No such file or directory: 'PTAscrawl.xlsx'

